# Site settings
title: jkzx
email: jk222zx@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jk222zx.github.io" # the base hostname & protocol for your site
twitter_username: No twitter - sorry.
github_username:  jk222zx

# Build settings
markdown: kramdown
